addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.0")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"       % "0.9.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.6.1")
//addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.20")
addSbtPlugin("org.wartremover"           % "sbt-wartremover"     % "2.4.16")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.10")
